== Actuator

Parametry życiowe i wydajnościowe instancji

=== Zależność 

spring-boot-actuator

=== Kanały

** HTTP

*** http endpoints jak : /actuator, /info, /health etc

** JMX

*** Monitoring i zarządzanie przez JMX

 Domyślnie Spring Boot tworzy instancje MBeanServer i wystawia interfejsy @adnotowane przez 

**** @ManagedResource

**** @ManagedAttribute

****  @ManagedOperation
 
** SSH

*** remote shell 


=== HealthEndpoint   [TODO/uzupelnic]

===  Własny Health endpoint / HealthIndicator

[source,java]
----
@Component
public class ActiveMQHealth implements HealthIndicator {
private ConnectionFactory factory;
@Autowired
public ActiveMQHealth(ConnectionFactory factory) {
   this.factory = factory;
}
@Override
public Health health() {
    try {
      factory.createConnection();
    } catch (JMSException e) {
      return new Health.Builder().down(e).build();
    }
 return new Health.Builder().status(Status.UP + ": Successfully connected tothe broker").build();
}
}
----

=== InfoEndpoint  [TODO/uzupelnic]


** **/autoconfig** - wyświetla co zostało skonfigurowane automatycznie 

** **/beans** - wyświetla wszystkie bean'y zarejestrowane w aplikacji

** **/configprops** - wszystkie konfiguracje properties

** **/dump** - dump report 

** **/env **- report o bieżących ustawieniach systemowych

** **/health** - prosty raport funkcji życiowych aplikacji

----
curl localhost:8090/health      h                                                                                                                                                    
{"status":"UP","diskSpace":{"status":"UP","total":219353915392,"free":127528636416,"threshold":10485760},"mongo":{"status":"UP","version":"2.6.10"}}
----

** **/info** - serwuje informacje o bieżącej konfiguracji aplikacji

** **/metrics** - metryki dotyczące punktów końcowych, sterty, wątków, gc, class loading etc

Dodatkowo dla każdej strony trzyma statusy HTTP, licznik wywołań, gauge.response

----
{

    "mem": 1132031,
    "mem.free": 485640,
    "processors": 8,
    "instance.uptime": 1079395,
    "uptime": 1088537,
    "systemload.average": 1.09,
    "heap.committed": 1048576,
    "heap.init": 1048576,
    "heap.used": 561152,
    "heap": 2097152,
    "nonheap.committed": 84928,
    "nonheap.init": 2496,
    "nonheap.used": 83457,
    "nonheap": 0,
    "threads.peak": 42,
    "threads.daemon": 38,
    "threads.totalStarted": 79,
    "threads": 42,
    "classes": 10148,
    "classes.loaded": 10148,
    "classes.unloaded": 0,
    "gc.g1_young_generation.count": 4,
    "gc.g1_young_generation.time": 141,
    "gc.g1_old_generation.count": 0,
    "gc.g1_old_generation.time": 0,
    "gauge.servo.response.health": 8.0,
    "gauge.servo.rest.totaltime": 0.008942816666666667,
    "gauge.servo.rest.count": 0.016666666666666666,
    "gauge.servo.rest.min": 1.155877,
    "gauge.servo.rest.max": 1.155877,
    "gauge.servo.response.api.applications": 3.0,
    "httpsessions.max": -1,
    "httpsessions.active": 0

}
----

** **/mappings** - wszystkie mapowania URL w aplikacji

** **/trace** - detale wcześniejszy requestów

----
{

    "timestamp": 1468504478026,
    "info": {
        "method": "POST",
        "path": "/api/applications",
        "headers": {
            "request": {
                "accept": "application/json",
                "content-type": "application/json",
                "user-agent": "Java/1.8.0_91",
                "host": "localhost:8090",
                "connection": "keep-alive",
                "content-length": "273"
            },
            "response": {
                "X-Application-Context": "CEP:dev:8090",
                "Content-Type": "application/json;charset=UTF-8",
                "Transfer-Encoding": "chunked",
                "Date": "Thu, 14 Jul 2016 13:54:38 GMT",
                "status": "201"
            }
        }
    }

},
{

    "timestamp": 1468504468058,
    "info": {
        "method": "GET",
        "path": "/api/journal",
        "headers": {
            "request": {
                "host": "localhost:8090",
                "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0",
                "accept": "text/event-stream",
                "accept-language": "pl,en-US;q=0.7,en;q=0.3",
                "accept-encoding": "gzip, deflate",
                "referer": "http://localhost:8090/index.html",
                "cookie": "__utma=111872281.2131442542.1458644832.1458644832.1461744507.2; __utmz=111872281.1458644832.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.1.2131442542.1458644832; auth_token=5b97a1d44bf087ab990369e6d6e2d55c413994d4; JSESSIONID=F70300B2C0A464FA47C28817326F8988",
                "connection": "keep-alive",
                "pragma": "no-cache",
                "cache-control": "no-cache"
            },
            "response": {
                "X-Application-Context": "CEP:dev:8090",
                "Content-Type": "text/event-stream;charset=UTF-8",
                "Transfer-Encoding": "chunked",
                "Date": "Thu, 14 Jul 2016 13:54:28 GMT",
                "status": "200"
            }
        }
    }

},...
----

=== remote shell

----
spring-boot-starter-remote-shell
----

** Polecenie : **ssh -p 2000 user@localhost** 


** Parametryzowanie wtyczki :

----
shell.ssh.port
shell.auth.simple.user.name
shell.auth.simple.user.password
----


=== Własne metryki 

** CounterService

[source,java]
----
...
final private CounterService counterService;
counterService.increment("messages.total.book.added");

----

*** increment

*** decrement

*** reset

** GaugeService


=== Trwałe metryki 


** MetricRepository

** MetricReader

** MetricWriter

Dostarczene przez  : **InMemoryMetricRepository**, **RedisMetricRepository**

=== Dostrajanie portów

----
management.port=9991
management.address=127.0.0.1
management.context-path=/manage
----

** Tylko JMX

----
management.port=-1
----


=== Rozszerzenia : 

** http://www.dropwizard.io/[Dropwizard]

** io.dropwizard.metrics:metrics-graphite


=== Inspekcja  [TODO/uzupelnic]

** **ApplicationEventPublisher**

** **ApplicationEventPublisherAware**

** **AuditEventRepository**

** **AuditApplicationEvent**

** **TraceRepository**

** **ApplicationPidFileWriter**