= SpringBoot camp
:docInfo1
:numbered:
:icons: font
:pagenums:
:imagesdir: images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../images]
:source-highlighter: coderay


== O mnie
* Architect Solution - RiscoSoftware 
* VavaTech trener : Spring ekosystem, JPA , EIP Camel 
* Sages trener : JPA , EIP - Apache Camel 
* blog link:http://przewidywalna-java.blogspot.com[]
* twitter przodownikR1

image:{image-link} [role='img-circle']


include::introduce.adoc[]

include::maven.adoc[]

include::gradle.adoc[]

== Java

----
spring run *.java
----


== Uruchamianie jako jar package

$ java -jar target/myproject-0.0.1-SNAPSHOT.jar

$ java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -jar target/myproject-0.0.1-SNAPSHOT.jar


include::starters.adoc[]


include::conditional.adoc[]

== Debug mode

----
debug=true
----


== Hot swapping

** JRebel
 
**  Spring Loaded


== Banner

Podłącznie baneru będzie wykonywane automatycznie gdy plik **banner.txt, banner.gif, banner.jpg czy banner.png** 
znajdą się na classpath lub zostaną jawnie określone przez zmienną  **banner.image.location** 


**${application.version}**  - wesja aplikacji zadeklarowana w MANIFEST.MF 

----
Implementation-Version: 1.0 wyświetli 1.0.
----


**${spring-boot.version}** - wesja Spring Boot użytego w aplikacji

**${application.title}**  - tytył aplikacji zadeklarowany w MANIFEST.MF.

----
Implementation-Title: MyApp wyślietli  MyApp.
----
 
    

NOTE: SpringApplication.setBanner(…​) Generowanie banneru programowalnie. (org.springframework.boot.Banner -> printBanner() method)

----
spring:
    main:
        banner-mode: "off"
        
----


               
[source,java]
----
public static void main(String[] args) {
    SpringApplication app = new SpringApplication(MySpringConfiguration.class);
    app.setBannerMode(Banner.Mode.OFF);
    app.run(args);
}

----
  
=== Fluent builder API

----

new SpringApplicationBuilder()
    .bannerMode(Banner.Mode.OFF)
    .sources(Parent.class)
    .child(Application.class)
    .run(args);
    
----
 
 
 
== Application events and listeners

**ApplicationStartedEvent** - odpalany podczas startu aplikacji, przed procesowaniem z wyjątkiem rejestracji słuchaczy czy initializerów.

**ApplicationEnvironmentPreparedEvent** - kiedy Environment zostanie użyty w kontekscie, ale przed stworzeniem kontekstu   

**ApplicationPreparedEvent** -   wywoływany przed odświeżeniem  aplikacji ale po załadowaniu wszystkich definicji modułów.

**ApplicationReadyEvent** - wywoływany po odświeżeniu lub wywołaniu jakiegokolwiek wywołania zwrotnego które zostało przeprocesowane w aplikacji 

**ApplicationFailedEvent** - wywołany podczas wystąpienie wyjątku na starcie

  
==  Argumenty wywołania


[source,java]
----
@Component
public class MyBean {

    @Autowired
    public MyBean(ApplicationArguments args) {
        boolean debug = args.containsOption("debug");
        List<String> files = args.getNonOptionArgs();
        // if run with "--debug logfile.txt" debug=true, files=["logfile.txt"]
    }

}

----

== Parametry z 'command line'

----
 java -jar -Dspring.profiles.active=production kataBoot-0.0.1-SNAPSHOT.jar
 java -jar -Dserver.port=8989 kataBoot-0.0.1-SNAPSHOT.jar 
----

----
--server.port=9000
----


----
set SERVER_PORT=9999 // on windows machine
export SERVER_PORT=9999 // on linux
----



== Admin features

spring.application.admin.enabled

include::extendConfig.adoc[]

== CommandLineRunner

[source,java]
----
public  void run(String...   args){
...
}
----

Zapewnia, że Spring Boot wykona daną metodę tylko raz zaraz po starcie


NOTE:  InitializingBean jako analogia

** Przykład

[source,java]
----
 @Autowired
    private Environment env;
    
    @Bean
    InitializingBean bean(){
        return () -> log.info("!!!!  application.user : {}",env.getProperty(APPLICATION_USER));
        
    }
----


** Przykład 2 / @Autowired repository

[source,java]
----
@Bean
	InitializingBean populateDatabase(CarRepository repository) {
		return () -> {
			repository.save(new Car("Honda", "Civic", "red"));
			repository.save(new Car("Fiat", "Uno", "black"));
			repository.save(new Car("Ford", "Escort", "black"));
		};
}
----

== ApplicationArguments


include::devtools.adoc[]


include::logging.adoc[]

include::web.adoc[]

include::orm.adoc[]

include::springData.adoc[]

include::nosql.adoc[]

== Using ResourceBundles for Internationalization (I18N)


include::security.adoc[]


include::cache.adoc[]


include::messaging.adoc[]


include::actuator.adoc[] 

== Sending email

=== Zależność 

----
spring-boot-starter-mail
----

Jeśli jest dostępna zależność i ustawiony parametr spring.mail.host JavaMailSender jest tworzony jeśli nie istnieje. 

=== Parametryzacja 

----
prefix : spring.mail namespace
----
 

include::test.adoc[]



