= SpringBoot camp
:docInfo1
:numbered:
:icons: font
:pagenums:
:imagesdir: img
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../img]
:source-highlighter: coderay


== O mnie
* Architect Solution - RiscoSoftware 
* VavaTech trener : Spring ekosystem, JPA , EIP Camel 
* Sages trener : JPA , EIP - Apache Camel 
* blog link:http://przewidywalna-java.blogspot.com[]
* twitter przodownikR1

image:{image-link} [role='img-circle']


== Co to jest Spring Boot ?


== Cechy

** Eliminacja XML

** Fluent SpringApplicationBuilder 

** Wbudowany kontener Tomcat lub Jetty

** ApplicationArguments

** Zcentralizowana konfiguracja 

*** application.properties

*** application.yml

** Profile

** Prostota konfiguracji zależności

** Prostota konfiguracji aplikacji

** Monitoring

*** Actuator

** Microservices :)




=== Pierwsza prosta aplikacja



== Strona projektu 

http://projects.spring.io/spring-boot/[spring boot]

== Dokumentacja 

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[dokumentacja]



== Spring vs Spring Boot

=== Podejście standardowe

** Projekt webowy musi zawierać folder WEB-INF

*** opjonalny plik : web.xml

*** <servlet-name>-servlet.xml


** Prosty kontroller 


[source,java]
----
@Controller
@EnableAutoConfiguration
public class SampleController {

    @RequestMapping("/")
    @ResponseBody
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SampleController.class, args);
    }
}
----


[source,java]
----
@RestController
public class SimpleWebController {
@RequestMapping("/")
public String greetings(){
return "Hello world";
}
}
----


== Uruchamianie 

=== Maven

** Konfiguracja 

[source,xml]
----

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

<modelVersion>4.0.0</modelVersion>
<groupId>com.example</groupId>
<artifactId>myapp</artifactId>
<version>0.0.1-SNAPSHOT</version>

<parent>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.6.RELEASE</version>
</parent>

<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        ...
</dependencies>

<build>
<plugins>
  <plugin>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-maven-plugin</artifactId>
   </plugin>
</plugins>
</build>
</project>
----

----
mvn spring-boot:run
----

=== Gradle

** Konfiguracja 

[source,groovy]
----
buildscript {
repositories {
jcenter()
maven { url "http://repo.spring.io/snapshot" }
maven { url "http://repo.spring.io/milestone" }
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.6.RELEASE")
}
}

apply plugin: 'java'
apply plugin: 'spring-boot'
jar {
   baseName = 'mySimpleApp'
   version = '0.0.1-SNAPSHOT'
}
repositories {
   jcenter()
   ...
}
dependencies {
   compile 'org.springframework.boot:spring-boot-starter' 
   compile("org.springframework.boot:spring-boot-starter-web")
   testCompile("org.springframework.boot:spring-boot-starter-test")
}
----
 
----
gradle bootRun
----



=== Java

----
spring run *.java
----

== Starters

** **spring-boot-starter**
    

The core Spring Boot starter, including auto-configuration support, logging and YAML.

** **spring-boot-starter-actuator**
    

Production ready features to help you monitor and manage your application.

** **spring-boot-starter-amqp**
    

Support for the “Advanced Message Queuing Protocol” via spring-rabbit.

** **spring-boot-starter-aop**
    

Support for aspect-oriented programming including spring-aop and AspectJ.

** **spring-boot-starter-artemis**
    

Support for “Java Message Service API” via Apache Artemis.

** **spring-boot-starter-batch**
    

Support for “Spring Batch” including HSQLDB database.

** **spring-boot-starter-cache**
    

Support for Spring’s Cache abstraction.

** **spring-boot-starter-cloud-connectors**
    

Support for “Spring Cloud Connectors” which simplifies connecting to services in cloud platforms like Cloud Foundry and Heroku.

** **spring-boot-starter-data-elasticsearch**
    

Support for the Elasticsearch search and analytics engine including spring-data-elasticsearch.

** **spring-boot-starter-data-gemfire**
    

Support for the GemFire distributed data store including spring-data-gemfire.

** **spring-boot-starter-data-jpa**
    

Support for the “Java Persistence API” including spring-data-jpa, spring-orm and Hibernate.

** **spring-boot-starter-data-mongodb**
    

Support for the MongoDB NoSQL Database, including spring-data-mongodb.

** **spring-boot-starter-data-rest**
    

Support for exposing Spring Data repositories over REST via spring-data-rest-webmvc.

** **spring-boot-starter-data-solr**
    

Support for the Apache Solr search platform, including spring-data-solr.

** **spring-boot-starter-freemarker**
    

Support for the FreeMarker templating engine.

** **spring-boot-starter-groovy-templates**
    

Support for the Groovy templating engine.

** **spring-boot-starter-hateoas**
    

Support for HATEOAS-based RESTful services via spring-hateoas.

** **spring-boot-starter-hornetq**
    

Support for “Java Message Service API” via HornetQ.

** **spring-boot-starter-integration**
    

Support for common spring-integration modules.

** **spring-boot-starter-jdbc**
    

Support for JDBC databases.

** **spring-boot-starter-jersey**
    

Support for the Jersey RESTful Web Services framework.

** **spring-boot-starter-jta-atomikos**
    

Support for JTA distributed transactions via Atomikos.

** **spring-boot-starter-jta-bitronix**
    

Support for JTA distributed transactions via Bitronix.

** **spring-boot-starter-mail**
    

Support for javax.mail.

** **spring-boot-starter-mobile**
    

Support for spring-mobile.

** **spring-boot-starter-mustache**
    

Support for the Mustache templating engine.

** **spring-boot-starter-redis**
    

Support for the REDIS key-value data store, including spring-redis.

** **spring-boot-starter-security**
    

Support for spring-security.

** **spring-boot-starter-social-facebook**
    

Support for spring-social-facebook.

** **spring-boot-starter-social-linkedin**
    

Support for spring-social-linkedin.

** **spring-boot-starter-social-twitter**
    

Support for spring-social-twitter.

** **spring-boot-starter-test**
    

Support for common test dependencies, including JUnit, Hamcrest and Mockito along with the spring-test module.

** **spring-boot-starter-thymeleaf**
    

Support for the Thymeleaf templating engine, including integration with Spring.

** **spring-boot-starter-velocity**
    

Support for the Velocity templating engine.

** **spring-boot-starter-web**
    

Support for full-stack web development, including Tomcat and spring-webmvc.

** **spring-boot-starter-websocket**
    

Support for WebSocket development.

** **spring-boot-starter-ws**
    

Support for Spring Web Services.

** **spring-boot-starter-actuator**
    

Adds production ready features such as metrics and monitoring.

** **spring-boot-starter-remote-shell**
    

Adds remote ssh shell support.

** **spring-boot-starter-jetty**
    

Imports the Jetty HTTP engine (to be used as an alternative to Tomcat).

** **spring-boot-starter-log4j**
    

Support the Log4J logging framework.

** **spring-boot-starter-logging**
    

Import Spring Boot’s default logging framework (Logback).

** **spring-boot-starter-tomcat**
    

Import Spring Boot’s default HTTP engine (Tomcat).

** **spring-boot-starter-undertow**
    

Imports the Undertow HTTP engine (to be used as an alternative to Tomcat).

== @Conditional

== Konfiguracja 

== CommandLineRunner

== ApplicationArguments

== @Enable



== Narzędzia

=== Spring Boot CLI

----
spring init -dweb,data-jpa,h2,thymeleaf --build gradle mySimpleApp --force
----

=== STS

=== https://start.spring.io/[Initializr]

== Logowanie

== Kolejki

== Rest

== ORM

== NoSql

== Using ResourceBundles for Internationalization (I18N)


== Security


== Actuator




