= SpringBoot camp
:docInfo1
:numbered:
:icons: font
:pagenums:
:imagesdir: img
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../img]
:source-highlighter: coderay


== O mnie
* Architect Solution - RiscoSoftware 
* VavaTech trener : Spring ekosystem, JPA , EIP Camel 
* Sages trener : JPA , EIP - Apache Camel 
* blog link:http://przewidywalna-java.blogspot.com[]
* twitter przodownikR1

image:{image-link} [role='img-circle']


== Co to jest Spring Boot ?


== Cechy

** Eliminacja XML

** Fluent SpringApplicationBuilder 

** Wbudowany kontener Tomcat lub Jetty

** ApplicationArguments

** Zcentralizowana konfiguracja 

*** application.properties

*** application.yml

** Profile

** Prostota konfiguracji zależności

** Prostota konfiguracji aplikacji

** Monitoring

*** Actuator

** Microservices :)




=== Pierwsza prosta aplikacja



== Strona projektu 

http://projects.spring.io/spring-boot/[spring boot]

== Dokumentacja 

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[dokumentacja]



== Spring vs Spring Boot

=== Podejście standardowe

** Projekt webowy musi zawierać folder WEB-INF

*** opjonalny plik : web.xml

*** <servlet-name>-servlet.xml


** Prosty kontroller 


[source,java]
----
@Controller
@EnableAutoConfiguration
public class SampleController {

    @RequestMapping("/")
    @ResponseBody
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SampleController.class, args);
    }
}
----


[source,java]
----
@RestController
public class SimpleWebController {
@RequestMapping("/")
public String greetings(){
return "Hello world";
}
}
----


== Uruchamianie 

=== Maven

** Konfiguracja 

[source,xml]
----

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

<modelVersion>4.0.0</modelVersion>
<groupId>com.example</groupId>
<artifactId>myapp</artifactId>
<version>0.0.1-SNAPSHOT</version>

<parent>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.6.RELEASE</version>
</parent>

<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        ...
</dependencies>

<build>
<plugins>
  <plugin>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-maven-plugin</artifactId>
   </plugin>
</plugins>
</build>
</project>
----

----
mvn spring-boot:run
----

=== Gradle

** Konfiguracja 

[source,groovy]
----
buildscript {
repositories {
jcenter()
maven { url "http://repo.spring.io/snapshot" }
maven { url "http://repo.spring.io/milestone" }
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.6.RELEASE")
}
}

apply plugin: 'java'
apply plugin: 'spring-boot'
jar {
   baseName = 'mySimpleApp'
   version = '0.0.1-SNAPSHOT'
}
repositories {
   jcenter()
   ...
}
dependencies {
   compile 'org.springframework.boot:spring-boot-starter' 
   compile("org.springframework.boot:spring-boot-starter-web")
   testCompile("org.springframework.boot:spring-boot-starter-test")
}
----
 
----
gradle bootRun
----



=== Java

----
spring run *.java
----


== @Conditional

== Konfiguracja

=== Spring Boot autoconfiguration

** spring-boot-starter-*

** AutoConfiguration

==== Przykłady 

** RepositoryRestMvcAutoConfiguration
** JpaRepositoriesAutoConfiguration
** JmsAutoConfiguration
** etc

** Wyłączanie danych elementów : 
[source,java]
----
@EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class})
----
 
=== Zmiana lokacji pliku z ustawieniami

spring.config.name= # config file name
spring.config.location= # location of config file

=== Własne ustawienia


=== .yaml


=== Wiele konfiguracji 


=== Przykłady 

-Dhost.port =9090

[source,xml]
----
mvn -Dspring.profiles.active=prod package

mvn -Dspring.profiles.active=dev package

----
** @ActiveProfiles("test") 
 

== CommandLineRunner

== ApplicationArguments

== @Enable



== Narzędzia

=== Spring Boot CLI

http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.3.5.RELEASE/spring-boot-cli-1.3.5.RELEASE-bin.zip[ostatnia wersja]

----
spring init -dweb,data-jpa,h2,thymeleaf --build gradle mySimpleApp --force
----

=== STS

=== https://start.spring.io/[Initializr]

== Adnotatacje

** @SpringBootApplication

[source,java]
----
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@Configuration
@EnableAutoConfiguration
@ComponentScan
public @interface SpringBootApplication {

----

== Properties

application.properties

== Logowanie


== WEB

=== Tomcat & JETTY

[source,xml]
----
<dependencies>
    <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
        <exclusions>
            <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jetty</artifactId>
    </dependency>
</dependencies>
----

== Kolejki

== Rest

== ORM

== NoSql

== Using ResourceBundles for Internationalization (I18N)


== Security


== Actuator

== Testowanie

[source,java]
----
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = MyApp.class)
@WebIntegrationTest
public class ApplicationTests {
@Test
public void testRestService() {
RestTemplate restTemplate = new RestTemplate();
Hello hello = restTemplate.getForObject("http://localhost:8080", Hello.class);
Assert.assertEquals("Hello World!", hello.getMessage());
}
}
----

** @WebIntegrationTest - zapewnia, że test bedzie odpalony na działającym serwerze 

NOTE: Alternatywa to : @WebAppConfiguration i  @IntegrationTest
 


