:numbered:
:icons: font
:pagenums:
:imagesdir: images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../images]
:source-highlighter: coderay

exercise.txt

Za pomoca narzędzia IDE lub ze strony spring.io

wygeneruj szkielet aplikacji 

Stwórz model Person


Stwórz repozytorium do person


Stwórz prosty kontroller, który wykona operacje CRUD na obiekcie domenowym Person



KOPIA :Projektowanie REST-ful API ze Springiem

dodaj do zależności:
spring-boot-starter-hateoas
dodaj proste operacje CRUD dla rezerwacji operujące na kolekcji obiektów w pamięci
dodaj metodę wyszukiwania rezerwacji po nazwie rezerwującego
dodaj nagłówek Location gdy tworzona jest rezerwacja wykorzystując:
ResponseEntity#created
ControllerLinkBuilder#linkTo
ControllerLinkBuilder#methodOn



spring-boot-starter-parent
spring-boot-starter-data-jpa
@EnableJpaRepositories
schema.sql
data.sql



Abstrakcja Repository



Repository
CustomerRepository
PagingAndSortingRepository
JpaRepository
@NoRepositoryBean




findBy*
Lastname
LastnameAndFirstname
LastnameOrFirstname
AgeLessThan
StartDateAfter
FirstnameStartingWith
...

Specyfikacje


JpaSpecificationExecutor
List<T> findAll(Specification<T> spec)

QueryDslJpaRepository
List<T> findAll(Predicate predicate)


Metody niestandardowe



interface UserRepositoryCustom

class UserRepositoryImpl  implements UserRepositoryCustom

interface UserRepository extends CrudRepository<User, Long>, UserRepositoryCustom


wsparcie dla Web MVC

@EnableSpringDataWebSupport
DomainClassConverter
HandlerMethodArgumentResolvers
Pageable
Sort


Thymeleaf użyj i skonfiguruj.

----
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8" />
    <title></title>
    <link rel="stylesheet" th:href="@{/style.css}"></link>
</head>
<body>
<p>
    <span th:text="${hello}">Hello!</span>
</p>
</body>
</html>
----

style.css

----
body {
    font-size: 12px;
}
----




Spring Data REST



spring-boot-starter-data-rest
RepositoryRestMvcAutoConfiguration
spring.data.rest.*
RepositoryRestConfiguration
@RepositoryRestResource
ResourceProcessor



odaj do zależności:
com.h2database:h2
spring-boot-starter-data-jpa
spring-boot-starter-data-rest
dodaj adnotacje JPA do modelu rezerwacji
dodaj JpaRepository dla rezerwacji i oznacz je jako @RepositoryRestResource
dodaj metodę wyszukiwania rezerwacji po nazwie rezerwującego
dodaj CommandLineRunner wpisujący do bazy kilka rekordów
dodaj ResourceProcessor<Resource<Reservation>> dodając link do zdjęcia w postaci odwołania do wyszukania w grafikach google


napisz własny repositoryCounter jako moduł :

**  autoconfig


----
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Import(RepoCounterConfiguration.class)
@Documented
public  @interface  EnableRepoCounting    {
}
----
** healthStatus


----
 private final Collection<CrudRepository<?,Long>> repositories;

    public DbCountRunner(Collection<CrudRepository<?,Long>> repositories) {
        this.repositories = repositories;
    }

    @Override
    public void run(String... args) throws Exception {
        repositories.forEach(
                crudRepository -> log.info("repo : {} , {} : entries", getRepositoryName(crudRepository.getClass()), crudRepository.count()));
    }

    private static String getRepositoryName(Class<? extends CrudRepository> crudRepositoryClass) {
        for (Class repositoryInterface : crudRepositoryClass.getInterfaces()) {
            if (repositoryInterface.getName().startsWith("{your_package_with_repo}")) {
                return repositoryInterface.getSimpleName();
            }
        }
        return "UnknownRepository";
    }
----



----
 private final Collection<CrudRepository<?,Long>> repositories;

    public DbCountRunner(Collection<CrudRepository<?,Long>> repositories) {
        this.repositories = repositories;
    }

    @Override
    public void run(String... args) throws Exception {
        repositories.forEach(
                crudRepository -> log.info("repo : {} , {} : entries", getRepositoryName(crudRepository.getClass()), crudRepository.count()));
    }

    private static String getRepositoryName(Class<? extends CrudRepository> crudRepositoryClass) {
        for (Class repositoryInterface : crudRepositoryClass.getInterfaces()) {
            if (repositoryInterface.getName().startsWith("{your_package_with_repo}")) {
                return repositoryInterface.getSimpleName();
            }
        }
        return "UnknownRepository";
    }
----

----
@NoArgsConstructor
public class DbCountRunner implements HealthIndicator {
    @Autowired
    private Collection<CrudRepository<?, Long>> repositories;
    
      @SuppressWarnings("boxing")
    @Override
    public Health health() {
    
    ...
    
----


napisz test persystencji encji rezerwacji
napisz test serializacji encji rezerwacji
napisz test integracyjny MVC potwierdzający że link do zdjęcia jest zwrócony dla daej rezerwacji




odaj zależności:
spring-boot-starter-actuator
org.springframework.data:spring-data-rest-hal-browser
dodaj swój własny HealthIndicator
dodaj wersję i nazwę artefaktu do /info
przejrzyj API acutator’a przy pomocy przeglądarki HAL






dodaj zależności:
spring-boot-starter-remote-shell
zaloguj się na swoją aplikację przez ssh



Zastosuj spring Security 

Basic HTTP 

Login Form

SSO - OAuth2

----
security.oauth2.client.access-token-uri=https://github.com/login/oauth/access_token
security.oauth2.client.user-authorization-uri=https://github.com/login/oauth/authorize
security.oauth2.client.client-authentication-scheme=form
security.oauth2.resource.user-info-uri=https://api.github.com/user

security.oauth2.client.client-id=***
security.oauth2.client.client-secret=***
----


----
@Configuration
@EnableOAuth2Sso
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    // @formatter:off
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .antMatchers(HttpMethod.GET, "/customer/{id}").permitAll()
                .antMatchers(HttpMethod.GET, "/customer").hasRole("USER")
                .antMatchers("/news/**").hasRole("ADMIN")
                .antMatchers("/about", "/contact","/github/page/**").permitAll()
                .antMatchers("/", "/js/**", "/login/**", "/css/**", "/img/**", "/webjars/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .csrf()
                .ignoringAntMatchers("/admin/h2-console/*")
                .and()
                .formLogin()
                .loginPage("/login")
                .permitAll()
                .and()
                .logout()
                .logoutSuccessUrl("/")
                .permitAll()
                .and()
                .headers()
.frameOptions().sameOrigin();
    }
 // @formatter:on
}
----

